# Arabic Reviews Sentiment Analysis

## Data Loading

In [2]:
import pandas as pd

reviews = pd.read_csv('data/CompanyReviews.csv')

reviews.head()

,Unnamed: 0,review_description,rating,company
0,0,رائع,1,talbat
1,1,برنامج رائع جدا يساعد على تلبيه الاحتياجات بشك...,1,talbat
2,2,التطبيق لا يغتح دائما بيعطيني لا يوجد اتصال با...,-1,talbat
3,3,لماذا لا يمكننا طلب من ماكدونالدز؟,-1,talbat
4,4,البرنامج بيظهر كل المطاعم و مغلقه مع انها بتكو...,-1,talbat

In [3]:
reviews.drop(columns=['Unnamed: 0', 'company'], inplace=True)

reviews.head()

                                  review_description  rating
0                                               رائع       1
1  برنامج رائع جدا يساعد على تلبيه الاحتياجات بشك...       1
2  التطبيق لا يغتح دائما بيعطيني لا يوجد اتصال با...      -1
3                 لماذا لا يمكننا طلب من ماكدونالدز؟      -1
4  البرنامج بيظهر كل المطاعم و مغلقه مع انها بتكو...      -1

## EDA

In [4]:
reviews['rating'].unique()

array([ 1, -1,  0])

In [11]:
for i in range(10):
    print(reviews['review_description'][i], reviews['rating'][i])

رائع 1
برنامج رائع جدا يساعد على تلبيه الاحتياجات بشكل اسرع 1
التطبيق لا يغتح دائما بيعطيني لا يوجد اتصال بالشبكة..مع انه النت عندي تمام شو الحل?? -1
لماذا لا يمكننا طلب من ماكدونالدز؟ -1
البرنامج بيظهر كل المطاعم و مغلقه مع انها بتكون فاتحه بقاله كده اكتر من شهر -1
أصبح غالي جداً -1
جميل جدا رائع. . . 1
للأسف الواحد ينصدم بعد زيادة الاسعار و للاسف بعض المطاعم اصبحت معاملتهم رديئة -1
برنامج توترز توصيل احلى من برنامجكم فاشل -1
كتير في تحسن خدمة العملاء لطفين في بعض الاخطاء التقنية لكن بتصلحوها بسرعة وبعض التاخير سياسيتكم وتسويقكم صار افضل من كريم بالنسبة الي متفقين 1

In [12]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40046 entries, 0 to 40045
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   review_description  40045 non-null  object
 1   rating              40046 non-null  int64
dtypes: int64(1), object(1)
memory usage: 625.8+ KB

In [14]:
reviews['review_description'].isna().value_counts()

review_description
False    40045
True         1
Name: count, dtype: int64

In [15]:
reviews.dropna(inplace=True)

reviews['review_description'].isna().value_counts()

review_description
False    40045
Name: count, dtype: int64

## Data Splitting

In [18]:
target = 'rating'

X = reviews.drop(target, axis=1)
y = reviews[target]

X.shape, y.shape

((40045, 1), (40045,))

In [19]:
from sklearn.model_selection import train_test_split

X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.2, stratify=y_train_full, random_state=42)

X_train.shape, X_val.shape, X_test.shape

((25628, 1), (6408, 1), (8009, 1))